const employee=[
    {
        name:"sagar",
        location:"chandigarh"
    },
    {
        name:"aman",
        location:"patiala"
    },
    {
        name:"aayush",
        location:"sonipat"
    },
    {
        name:"ani",
        location:"ropar"
    },

    {
        name:"khushwinder",
        location:"pathankot"
    },
    {
        name:"maa",
        location:"kothikohar"
    },
    {
        name:"mamta",
        location:"mumbai"
    },
    {
        name:"prem",
        location:"delhi"
    }
    ,
    {
        name:"papa",
        location:"bir"
    },{
        name:"ram",
        location:"bharat"
    },
    {
        name:"sham",
        location:"bharat"
    }
]
export default employee;